Balanca/ViewModels/ConsultaUsuarioViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Core.Objects.DataClasses;
using Balanca.Common.Enumerators;

namespace Balanca.ViewModels
{
    public class ConsultaUsuarioViewModels
    {

        public int UsuarioID { get; set; }
        public string Matricula { get; set; }
        public int EmpresaID { get; set; }
        public string CPF { get; set; }
        public string Nome { get; set; }

        public string Setor { get; set; }
        public string Cargo { get; set; }
        public DateTime DataNascimento { get; set; }
        public int Idade { get; set; }
        public string NomeEmpresa { get; set; }
        public int CODIGOEMPRESA { get; set; }
        public string CODIGOUNIDADE { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Sexo:")]
        public Enumerators.SexoEnum Sexo { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Qual sua escolaridade? Maior grau escolar concluído:")]
        public Enumerators.EscolaridadeEnum Escolaridade { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Qual o seu estado civil:")]
        public Enumerators.EstadoCivilEnum EstadoCivil { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você tem filhos ?")]
        public Enumerators.FilhosEnum Filhos { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Há quanto tempo você trabalha na empresa, em anos:")]
        public Enumerators.TempoServicoEmpresaAnosEnum TempoTrabalhoEmpresa { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Em sua opinião, o seu trabalho é fisicamente desgastante:")]
        public Enumerators.SimNaoUmPoucoMuitoEnum TrabalhoFisicamenteDesgastante { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Em sua opinião, o seu trabalho é psicologicamente desgastante:")]
        public Enumerators.SimNaoUmPoucoMuitoEnum TrabalhoPsicologicamenteExtressanete { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Qual seu consumo de álcool por semana? ")]
        public Enumerators.ConsumoAlcoolEnum ConsumoAlcoolSemanal { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você fuma, ou já fumou?")]
        public Enumerators.FumanteEnum Fumante { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você pratica atividades físicas?")]
        public Enumerators.SimNaoEnum PraticaAtividadeFisica { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Intensidade")]
        public Enumerators.IntensidadeAtividadesEnum Intensidade { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Quantas vezes por semana?")]
        public Enumerators.QuantidadeAtividadesEnum AtividadeFisicaIntensa { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você está satisfeito com o seu trabalho?")]
        public Enumerators.SatisfacaoTrabalhoEnum SatisfacaoTrabalho { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você está satisfeito com a vida?")]
        public Enumerators.SatisfacaoVidaEnum SatisfacaoVida { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você se sente estressado?")]
        public Enumerators.EstressadoEnum Estressado { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você tem sentindo insônia, sensação de angústia ou grande tristeza?")]
        public Enumerators.InsoniaEnum Insonia { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você possui cônjuge, amigo ou parente com quem pode contar em caso de dificuldade financeira, para desabafar ou solicitar ajuda?")]
        public Enumerators.SimNaoEnum ProximoDificuldadeFinanceira { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Em geral você diria que sua saúde é:")]
        public Enumerators.ClassificacaoSaudeEnum Saude { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você tem alguma doença que limite suas atividades em casa ou no trabalho?")]
        public Enumerators.SimNaoEnum DoencaLimiteAtividade { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Já houve necessidade de se afastar do trabalho por motivos de saúde ?")]
        public Enumerators.AfastadoPeloInss AfastamentoTrabalhoSaude { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você agenda suas consultas fora do horário de expediente?")]
        public Enumerators.ConsultaForaExpedienteEnum AgendaConsultasForaHorarioExp { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você sente dores contínuas nas costas, braços ou pernas?")]
        public Enumerators.SimNaoEnum DoresContinuaCostas { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Quantas porções por dia você consome dos seguintes alimentos: pão, bolacha, doces, refrigerante, mandioca, batata, arroz, macarrão, chipa, pão de queijo, tapioca, bolo? ")]
        public Enumerators.QuantidadePorcoesEnum QtdePorcoesConsumidaPorDia { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Quantas porções por dia você consome de frutas ou legumes ou verduras:")]
        public Enumerators.QuantidadeFrutasEnum QtdePorcoesFrutaLegumesPorDia { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você toma algum medicamento de Uso Contínuo?")]
        public Enumerators.SimNaoEnum TomaMedicamento { get; set; }
        [Display(Name = "Você tem alguma dessas doenças?")]
        public List<int?> Doencas { get; set; }
        [Display(Name = "Tipo de remédio?")]
        public List<int?> TipoMedicamento { get; set; }
    }


    public class LoginUsuariaoViewModel
    {
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "CPF")]
        public string CPF { get; set; }
    }

    public class TesteViewModel
    {
        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Você tem alguma dessas doenças?")]
        public List<Enumerators.DoencasEnum> Doencas { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Display(Name = "Tipo de remédio?")]
        public List<Enumerators.TipodeMedicacaoEnum> TipoMedicamento { get; set; }
    }
}

Balanca/Controllers/ConsultaUsuarioController.cs
using System;
using System.Linq;
using System.Web.Management;
using System.Web.Mvc;
using AutoMapper;
using Balanca.Common.Enumerators;
using Balanca.Entities.Balanca.Model;
using Balanca.Entities.Classes;
using Balanca.Entities.Repositorio;
using Balanca.ViewModels;

namespace Balanca.Controllers
{
    public class ConsultaUsuarioController : BaseController
    {
        private BalancaEntities db = new BalancaEntities();
        public ConsultaWsRepository repoConsultaWs = new ConsultaWsRepository();


        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginUsuariaoViewModel instancia)
        {
            if (ModelState.IsValid)
            {
                if (!String.IsNullOrEmpty(instancia.CPF))
                {

                    if (BuscarUsuarioBalanca(Convert.ToInt64(instancia.CPF)) != null || BuscarFuncionarioSoc(instancia.CPF) != null)
                        return RedirectToAction("Create", new { id = instancia.CPF });
                }

                Erro("Tentativa de login inválida, CPF não encontrado.", true);

            }

            return View(instancia);
        }


        public ActionResult Create(string id = "0")
        {
            UsuariosBalanca usuario = BuscarUsuarioBalanca(Convert.ToInt64(id));

            if (usuario != null)
            {
                ConsultaUsuarioViewModels u = Mapper.Map<UsuariosBalanca, ConsultaUsuarioViewModels>(usuario);
                u.Idade = CalculaIdade(u.DataNascimento);
                return View(u);
            }

            DadosFuncionarioSOC funcionario = BuscarFuncionarioSoc(id);
            if (funcionario != null)
            {
                ConsultaUsuarioViewModels c = new ConsultaUsuarioViewModels();
                c.Nome = funcionario.NOME;
                c.Setor = funcionario.NOMESETOR;
                c.Cargo = funcionario.NOMECARGO;
                c.DataNascimento = Convert.ToDateTime(funcionario.DATA_NASCIMENTO);
                c.Idade = CalculaIdade(c.DataNascimento);
                c.NomeEmpresa = funcionario.NOMEEMPRESA;
                c.CPF = funcionario.CPFFUNCIONARIO;
                c.Matricula = funcionario.MATRICULAFUNCIONARIO;
                c.CODIGOEMPRESA = (int)funcionario.CODIGOEMPRESA;
                c.CODIGOUNIDADE = funcionario.CODIGOUNIDADE.ToString();

                return View(c);
            }

            Erro("Tentativa de login inválida, CPF não encontrado.", true);
            return RedirectToAction("Login");
        }

        public string RetornarSexo(int codigoSexo)
        {
            return (codigoSexo == 1) ? "Masculino" : "Feminino";
        }

        public static int CalculaIdade(DateTime dtNascimento)
        {
            int idade = DateTime.Now.Year - dtNascimento.Year;
            if (DateTime.Now.Month < dtNascimento.Month || (DateTime.Now.Month == dtNascimento.Month && DateTime.Now.Day < dtNascimento.Day))
                idade--;

            return idade;
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ConsultaUsuarioViewModels instanciaView)
        {
            try
            {
                if (ModelState.IsValid && instanciaView.Doencas.Any())
                {
                    FormularioBalanca instancia = Mapper.Map<ConsultaUsuarioViewModels, FormularioBalanca>(instanciaView);
                    string numeroCracha = string.Empty;

                    EmpresasSOC emp = new EmpresaRepository().BuscarEmpresasSoc(instanciaView.CODIGOEMPRESA, instanciaView.CODIGOUNIDADE);

                    if (BuscarUsuarioBalanca(instancia.CPF) != null)
                    {
                        instancia.UsuariosBalanca = BuscarUsuarioBalanca(instancia.CPF);
                    }
                    else
                    {
                        UsuariosBalanca usuario = Mapper.Map<ConsultaUsuarioViewModels, UsuariosBalanca>(instanciaView);
                        usuario.DataCadastro = DateTime.Now;
                        usuario.Situacao = (int)Enumerators.StatusEnum.Ativo;
                        usuario.EmpresaID = emp.EmpresaID;
                        usuario.Sexo = (int)instanciaView.Sexo;
                        instancia.UsuariosBalanca = new UsuariosBalanca();
                        instancia.UsuariosBalanca = usuario;
                    }

                    instancia.UsuariosBalanca.EmpresasSOC = null;
                    instancia.DataCadastro = DateTime.Now;
                    instancia.Situacao = (int)Enumerators.StatusEnum.Ativo;



                    foreach (var doenca in instanciaView.Doencas)
                    {
                        if (doenca != null)
                        {
                            DoencasUsuario d = new DoencasUsuario { Valor = doenca.Value };
                            instancia.DoencasUsuario.Add(d);
                        }
                    }


                    if (instanciaView.TomaMedicamento == Enumerators.SimNaoEnum.Sim)
                    {
                        foreach (var medicao in instanciaView.TipoMedicamento)
                        {
                            if (medicao != null)
                            {
                                TipoMedicaoUsuario t = new TipoMedicaoUsuario { Valor = medicao.Value };
                                instancia.TipoMedicaoUsuario.Add(t);
                            }
                        }
                    }

                    db.FormularioBalanca.Add(instancia);
                    db.SaveChanges();

                    PessoaBalanca p = repoConsultaWs.CadastrarPessoaBalanca(instancia.UsuarioID, out string _msg);
                    if (p != null)
                    {
                        numeroCracha = emp.CodigoFolha + p.matricula.PadLeft(4, '0');
                        repoConsultaWs.CadastrarCrachaBalanca(p.idPessoa, numeroCracha);
                    }
                    else
                    {
                        Erro("Aviso : " + _msg, true);
                    }

                    Successo("Formulário salvo com sucesso, suba  na balança para continuar sua avaliação. ", true);
                    return RedirectToAction("Login");
                }
            }
            catch (Exception e)
            {
                Erro("Erro ao Salvar os dados :(" + e.Message);
                return View(instanciaView);
            }

            return View(instanciaView);
        }




        public DadosFuncionarioSOC BuscarFuncionarioSoc(string cpf)
        {
            return db.DadosFuncionarioSOC.FirstOrDefault(fs => fs.CPFFUNCIONARIO == cpf && fs.SITUACAO == "Ativo");
        }

        public UsuariosBalanca BuscarUsuarioBalanca(long cpf)
        {
            return db.UsuariosBalanca.FirstOrDefault(x => x.CPF == cpf);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Balanca/Views/ConsultaUsuario/Delete.cshtml
@model Balanca.Entities.Balanca.Model.ConsultasUsuario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ConsultasUsuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Casa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Casa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Setor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Setor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Escolaridade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Escolaridade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoCivil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoCivil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrabalhoFisicamenteDesgastante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrabalhoFisicamenteDesgastante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrabalhoPsicologicamenteExtressanete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrabalhoPsicologicamenteExtressanete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsumoAlcoolSemanal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsumoAlcoolSemanal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fumante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fumante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PraticaAtividadeFisica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PraticaAtividadeFisica)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AtividadeFisicaLeve)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AtividadeFisicaLeve)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AtividadeFisicaIntensa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AtividadeFisicaIntensa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SatisfacaoTrabalho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SatisfacaoTrabalho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SatisfacaoVida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SatisfacaoVida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estressado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estressado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Insonia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Insonia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProximoDificuldadeFinanceira)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProximoDificuldadeFinanceira)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Saude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Saude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoencaLimiteAtividade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoencaLimiteAtividade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AfastamentoTrabalhoSaude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AfastamentoTrabalhoSaude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgendaConsultasForaHorarioExp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgendaConsultasForaHorarioExp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoresContinuaCostas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoresContinuaCostas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtdePorcoesConsumidaPorDia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtdePorcoesConsumidaPorDia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtdePorcoesFrutaLegumesPorDia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtdePorcoesFrutaLegumesPorDia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDoenca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDoenca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TomaMedicamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TomaMedicamento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoMedicamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoMedicamento)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Balanca/Views/ConsultaUsuario/Login.cshtml
@model Balanca.ViewModels.LoginUsuariaoViewModel
@{
    ViewBag.Title = "Efetuar login";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}

<script>
    jQuery(document).ready(function () {
        $("#CPF").inputmask('999.999.999-99', { numericInput: true });

        $("#btnSubmit").on('click', function () {

            if (validarCPF($("#CPF").val())) {
                $("#FormLogin").submit();
            } else {
               
                swal({
                    customClass: 'swal-wide',
                    position: 'top',
                    type: 'error',
                    title: 'Erro',
                    html: "<h2>CPF '" + $("#CPF").val() + "' Inválido </h2>",
                    showConfirmButton: true,
                    timer: 10000
                });

                $("#CPF").val("");
                return false;
            }
        });

       

    });
    function validarCPF(cpf) {
        
        value = jQuery.trim(cpf);

        value = value.replace('.', '');
        value = value.replace('.', '');
        cpf = value.replace('-', '');

        if (cpf.length < 11) {
            return false;
        }

        while (cpf.length < 11) cpf = "0" + cpf;
        var expReg = /^0+$|^1+$|^2+$|^3+$|^4+$|^5+$|^6+$|^7+$|^8+$|^9+$/;
        var a = [];
        var b = new Number;
        var c = 11;
        for (i = 0; i < 11; i++) {
            a[i] = cpf.charAt(i);
            if (i < 9) b += (a[i] * --c);
        }
        if ((x = b % 11) < 2) { a[9] = 0 } else { a[9] = 11 - x }
        b = 0;
        c = 11;
        for (y = 0; y < 10; y++) b += (a[y] * c--);
        if ((x = b % 11) < 2) { a[10] = 0; } else { a[10] = 11 - x; }

        var retorno = true;

        if ((cpf.charAt(9) != a[9]) || (cpf.charAt(10) != a[10]) || cpf.match(expReg))
            retorno = false;
        return retorno;
            
    };

    function maxLengthCheck(object) {
        if (object.value.length > object.maxLength)
            object.value = object.value.slice(0, object.maxLength)
    }
    
    function isNumeric (evt) {
        var theEvent = evt || window.event;
        var key = theEvent.keyCode || theEvent.which;
        key = String.fromCharCode (key);
        var regex = /[0-9]|\./;
        if ( !regex.test(key) ) {
            theEvent.returnValue = false;
            if(theEvent.preventDefault) theEvent.preventDefault();
        }
    }
</script>

<div class="row" align="center">

    <div class="col-md-8 col-xs-8">

        @using (Html.BeginForm("Login", "ConsultaUsuario", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "FormLogin" }))
        {
            @Html.AntiForgeryToken()
            <div class="col-md-6 ">
                <br /><br />
            </div>
            <div class="col-md-offset-6 col-md-6 col-xs-8 col-xs-offset-5">
                <p style="text-align: center"><img src="~/images/SAUDE EM FORMA.png" width="250" height="150" />    </p>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="col-md-offset-6 col-md-6 col-xs-8 col-xs-offset-5">
                    @Html.TextBoxFor(m => m.CPF, new { @class = "form-control", placeholder = "CPF", type = "number", maxlength = "11", autofocus = true, onkeypress="return isNumeric(event)" , oninput="maxLengthCheck(this)" })
                    @Html.ValidationMessageFor(m => m.CPF, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-6 col-md-6 col-xs-8 col-xs-offset-5">

                    <button id="btnSubmit" type="button" class="btn btn-block btn-lg" style="color: #ffffff; background: #2DA158" aria-label="Acessar">
                        Acesse
                        <span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>
                    </button>
                </div>
            </div>
        }
        <div><br /><br /><br /><br /></div>
    </div>
</div>